version: '3'
services:
  database:
    image: database
    restart: always
    environment:
      POSTGRES_PASSWORD: "Pp123456789"
    networks:
      - mynet
      
  server:
    image: server
    restart: always
    depends_on:
      - database
    ports:
      - "5000:5000"
    environment:
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "Pp123456789"
      DB_NAME: "clarustodo"
    networks:
      - mynet
  client:
    image: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: always
    networks:
      - mynet
networks:
  mynet:
    driver: bridge

